"""Synthetic KORU grammar tests.

Residual source-capture acceptance item: retain and golden-test an actual KORU provider
archive and CHECKSUM when first-party bytes become available; these generated bytes do
not stand in for that evidence. The frozen BTC official fixture separately protects the
shared Binance USD-M aggTrades archive grammar.
"""

from __future__ import annotations

import hashlib
import io
from dataclasses import replace
from pathlib import Path
from zipfile import ZIP_STORED, ZipFile, ZipInfo

import pytest
from crypto_quant_bundle_builder.binance_usdm_koru_aggtrades_source_bounded_v1 import (
    BinanceUsdmKoruAggregateTradesSourceBoundedCaptureResultV1,
    BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1,
    BinanceUsdmKoruAggregateTradesSourceBoundedNormalizationOutcomeV1,
    BinanceUsdmKoruAggregateTradesSourceBoundedRequestV1,
    capture_binance_usdm_koru_aggregate_trades_source_bounded_v1,
    normalize_binance_usdm_koru_aggregate_trades_source_bounded_v1,
)
from crypto_quant_domain import InstrumentId, UtcInstant, VenueId
from crypto_quant_market_data import MarketEvent

UTC_DATE = "2026-07-16"
DAY_START_NS = 1_784_160_000_000_000_000
DAY_END_NS = 1_784_246_400_000_000_000
DAY_START_MS = DAY_START_NS // 1_000_000
ARCHIVE_AVAILABLE_AT = DAY_END_NS + 3_600_000_000_000
ACQUIRED_AT = 1_784_332_800_000_000_000
ROWS = (
    ("700", "12.340", "1.250", "900", "901", str(DAY_START_MS + 1_000), "true"),
    ("701", "12.350", "2.000", "902", "903", str(DAY_START_MS + 2_000), "false"),
    ("702", "12.360", "3.125", "904", "905", str(DAY_START_MS + 2_000), "true"),
)
SYNTHETIC_FIXTURE_CLASSIFICATION = "synthetic_generated_contract_fixture"
ACTUAL_PROVIDER_RESIDUAL_ACCEPTANCE_ITEM = (
    "capture_and_golden_actual_koru_provider_archive_and_checksum"
)


def sha256(value: bytes) -> str:
    return "sha256:" + hashlib.sha256(value).hexdigest()


def archive_bytes(
    rows: tuple[tuple[str, ...], ...] = ROWS,
    *,
    member_name: str = f"KORUUSDT-aggTrades-{UTC_DATE}.csv",
) -> bytes:
    csv_bytes = b"".join((",".join(row) + "\n").encode() for row in rows)
    output = io.BytesIO()
    info = ZipInfo(member_name, (2026, 7, 16, 0, 0, 0))
    info.compress_type = ZIP_STORED
    info.external_attr = 0o644 << 16
    with ZipFile(output, "w") as archive:
        archive.writestr(info, csv_bytes)
    return output.getvalue()


def evidence(
    rows: tuple[tuple[str, ...], ...] = ROWS,
    *,
    member_name: str = f"KORUUSDT-aggTrades-{UTC_DATE}.csv",
    checksum_name: str = f"KORUUSDT-aggTrades-{UTC_DATE}.zip",
    checksum_separator: str = "  ",
) -> tuple[bytes, bytes]:
    archive = archive_bytes(rows, member_name=member_name)
    checksum = (
        sha256(archive)[7:] + checksum_separator + checksum_name + "\n"
    ).encode()
    return archive, checksum


def request_for(
    archive: bytes,
    checksum: bytes,
    *,
    instrument_id: InstrumentId | None = None,
    utc_date: str = UTC_DATE,
    archive_available_at: int = ARCHIVE_AVAILABLE_AT,
    acquired_at: int = ACQUIRED_AT,
    expected_archive_sha256: str | None = None,
) -> BinanceUsdmKoruAggregateTradesSourceBoundedRequestV1:
    return BinanceUsdmKoruAggregateTradesSourceBoundedRequestV1(
        instrument_id
        or InstrumentId(VenueId("binance_usdm"), "koru-usdt-tradifi-perpetual"),
        utc_date,
        archive_available_at,
        acquired_at,
        expected_archive_sha256 or sha256(archive),
        sha256(checksum),
    )


class Fetch:
    def __init__(self, responses: dict[str, list[tuple[int, bytes] | Exception]]) -> None:
        self.responses = responses
        self.calls: list[str] = []

    def __call__(self, url: str) -> tuple[int, bytes]:
        self.calls.append(url)
        response = self.responses[url].pop(0)
        if isinstance(response, Exception):
            raise response
        return response


def capture(
    rows: tuple[tuple[str, ...], ...] = ROWS,
    *,
    member_name: str = f"KORUUSDT-aggTrades-{UTC_DATE}.csv",
    archive_available_at: int = ARCHIVE_AVAILABLE_AT,
) -> BinanceUsdmKoruAggregateTradesSourceBoundedCaptureResultV1:
    archive, checksum = evidence(rows, member_name=member_name)
    request = request_for(
        archive, checksum, archive_available_at=archive_available_at
    )
    archive_url, checksum_url = request.urls
    outcome = capture_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        request,
        Fetch({archive_url: [(200, archive)], checksum_url: [(200, checksum)]}),
    )
    assert outcome.failure is None
    assert outcome.result is not None
    return outcome.result


def normalize(
    rows: tuple[tuple[str, ...], ...] = ROWS,
    *,
    member_name: str = f"KORUUSDT-aggTrades-{UTC_DATE}.csv",
) -> BinanceUsdmKoruAggregateTradesSourceBoundedNormalizationOutcomeV1:
    return normalize_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        capture(rows, member_name=member_name)
    )


def test_fixture_is_explicitly_synthetic_and_actual_provider_capture_remains_residual() -> None:
    fixture_root = (
        Path(__file__).parents[3]
        / "fixtures/market_data/providers/binance_usdm"
    )
    assert SYNTHETIC_FIXTURE_CLASSIFICATION == "synthetic_generated_contract_fixture"
    assert ACTUAL_PROVIDER_RESIDUAL_ACCEPTANCE_ITEM == (
        "capture_and_golden_actual_koru_provider_archive_and_checksum"
    )
    assert not tuple(fixture_root.rglob("*KORUUSDT*"))
    assert archive_bytes() == archive_bytes()


def test_successful_capture_and_normalization_are_golden_and_replay_deterministic() -> None:
    captured = capture()
    outcome = normalize_binance_usdm_koru_aggregate_trades_source_bounded_v1(captured)
    replay = normalize_binance_usdm_koru_aggregate_trades_source_bounded_v1(captured)
    assert outcome.failure is replay.failure is None
    assert outcome.result is not None
    assert replay.result is not None
    result = outcome.result

    assert captured.request.urls == (
        (
            "https://data.binance.vision/data/futures/um/daily/aggTrades/KORUUSDT/"
            "KORUUSDT-aggTrades-2026-07-16.zip"
        ),
        (
            "https://data.binance.vision/data/futures/um/daily/aggTrades/KORUUSDT/"
            "KORUUSDT-aggTrades-2026-07-16.zip.CHECKSUM"
        ),
    )
    assert result.normalization_hash == replay.result.normalization_hash
    assert result.request_hash == captured.request.request_hash
    assert result.capture_hash == captured.capture_hash
    assert result.source_snapshot_id == captured.snapshot.snapshot_id
    assert result.source_snapshot_hash == captured.to_canonical_dict()["source_snapshot_hash"]
    assert result.requested_day_start == UtcInstant(DAY_START_NS)
    assert result.requested_day_end_exclusive == UtcInstant(DAY_END_NS)
    assert result.coverage_start == UtcInstant((DAY_START_MS + 1_000) * 1_000_000)
    assert result.coverage_end_exclusive == UtcInstant(
        (DAY_START_MS + 2_000) * 1_000_000 + 1
    )
    assert result.coverage_start > result.requested_day_start
    assert result.coverage_end_exclusive < result.requested_day_end_exclusive
    assert result.prefix_gap_classification == "unknown_unproven"
    assert result.suffix_gap_classification == "unknown_unproven"
    assert result.internal_gap_classification == "none_observed_by_contiguous_ids"
    assert result.row_count == 3
    assert result.first_aggregate_trade_id == 700
    assert result.last_aggregate_trade_id == 702
    assert result.decision_grade_eligible is False
    assert result.deployment_authorized is False

    first = result.events[0]
    assert first.instrument_id == InstrumentId(
        VenueId("binance_usdm"), "koru-usdt-tradifi-perpetual"
    )
    assert first.capability.identity == "price.aggregate_trade.koru-usdt-tradifi-perpetual@1"
    assert first.stream_key == (
        "binance_usdm.aggregate_trades.execution_reference.koruusdt.tradifi.v1"
    )
    assert first.event_type == "binance_usdm_koru_aggregate_trade.v1"
    assert first.event_time == UtcInstant((DAY_START_MS + 1_000) * 1_000_000)
    assert first.available_time == UtcInstant(ARCHIVE_AVAILABLE_AT)
    assert first.payload["aggregate_trade_id"] == 700
    assert first.payload["first_trade_id"] == 900
    assert first.payload["last_trade_id"] == 901
    assert first.payload["price"] == "12.340"
    assert first.payload["quantity"] == "1.250"
    assert first.payload["is_buyer_maker"] is True
    assert first.payload["archive_available_at_epoch_nanoseconds"] == ARCHIVE_AVAILABLE_AT
    assert first.payload["acquired_at_epoch_nanoseconds"] == ACQUIRED_AT
    assert first.payload["source_snapshot_id"] == captured.snapshot.snapshot_id
    assert first.payload["source_member_hash"] == result.source_member_hash
    assert str(ARCHIVE_AVAILABLE_AT) in captured.snapshot.provenance.source_key
    assert "btc" not in str(result.to_canonical_dict()).lower()

    assert captured.request.request_hash == (
        "sha256:cb861eb59772aa663e173322a31dd7acf79d7db91310577cbab1a699588c31af"
    )
    assert captured.capture_hash == (
        "sha256:5e20ef4492cecb8da863fab6c25637029bc2ee6becceabc7be25b33ea76c36cf"
    )
    assert first.event_hash == (
        "sha256:8c58ce4a42e9c9b1bff0490f7283ff12bc4f16be218a595f8b69392ed2bd8ff8"
    )
    assert result.normalization_hash == (
        "sha256:cc8f563043fe29d6e2e81747f5c64393c9353b43e335f0b82ba70e37ccdbf0d2"
    )


def test_archive_availability_is_bound_into_request_snapshot_and_event_lineage() -> None:
    first_capture = capture(archive_available_at=ARCHIVE_AVAILABLE_AT)
    second_capture = capture(archive_available_at=ARCHIVE_AVAILABLE_AT + 1)
    first_result = normalize_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        first_capture
    ).result
    second_result = normalize_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        second_capture
    ).result
    assert first_result is not None
    assert second_result is not None
    assert first_capture.request.request_hash != second_capture.request.request_hash
    assert first_capture.snapshot.snapshot_id == second_capture.snapshot.snapshot_id
    assert first_capture.snapshot.provenance_hash != second_capture.snapshot.provenance_hash
    assert first_result.events[0].available_time != second_result.events[0].available_time
    assert first_result.events[0].event_hash != second_result.events[0].event_hash


@pytest.mark.parametrize(
    ("archive_available_at", "acquired_at", "message"),
    [
        (DAY_START_NS - 1, ACQUIRED_AT, "requested UTC day end"),
        (DAY_START_NS + 1, ACQUIRED_AT, "requested UTC day end"),
        (DAY_END_NS - 1, ACQUIRED_AT, "requested UTC day end"),
        (DAY_END_NS + 1, DAY_END_NS, "acquired_at cannot precede"),
    ],
)
def test_request_rejects_before_day_intra_day_before_day_end_and_acquired_before_available(
    archive_available_at: int, acquired_at: int, message: str
) -> None:
    archive, checksum = evidence()
    with pytest.raises(ValueError, match=message):
        request_for(
            archive,
            checksum,
            archive_available_at=archive_available_at,
            acquired_at=acquired_at,
        )


def test_request_accepts_exact_day_end_availability_and_acquisition_boundary() -> None:
    archive, checksum = evidence()
    request = request_for(
        archive,
        checksum,
        archive_available_at=DAY_END_NS,
        acquired_at=DAY_END_NS,
    )
    assert request.archive_available_at_epoch_nanoseconds == DAY_END_NS
    assert request.acquired_at_epoch_nanoseconds == DAY_END_NS


def test_request_rejects_wrong_identity_date_hash_and_forged_fields() -> None:
    archive, checksum = evidence()
    with pytest.raises(ValueError, match="exact KORU"):
        request_for(
            archive,
            checksum,
            instrument_id=InstrumentId(
                VenueId("binance_usdm"), "btc-usdt-perpetual"
            ),
        )
    with pytest.raises(ValueError, match="on or after"):
        request_for(archive, checksum, utc_date="2026-07-14")
    with pytest.raises(ValueError, match="ISO UTC date"):
        request_for(archive, checksum, utc_date="2026-7-16")
    with pytest.raises(ValueError, match="canonical sha256"):
        BinanceUsdmKoruAggregateTradesSourceBoundedRequestV1(
            InstrumentId(
                VenueId("binance_usdm"), "koru-usdt-tradifi-perpetual"
            ),
            UTC_DATE,
            ARCHIVE_AVAILABLE_AT,
            ACQUIRED_AT,
            "sha256:not-a-hash",
            sha256(checksum),
        )

    forged = request_for(archive, checksum)
    object.__setattr__(
        forged,
        "instrument_id",
        InstrumentId(VenueId("binance_usdm"), "btc-usdt-perpetual"),
    )
    failed = capture_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        forged, lambda _: (200, b"")
    )
    assert failed.result is None
    assert failed.failure is not None
    assert failed.failure.code is BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.CONFIGURATION_INVALID


def test_capture_validates_expected_and_declared_hashes_checksum_and_member_name() -> None:
    archive, checksum = evidence()
    wrong_hash_request = request_for(
        archive,
        checksum,
        expected_archive_sha256="sha256:" + "0" * 64,
    )
    archive_url, checksum_url = wrong_hash_request.urls
    wrong_hash = capture_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        wrong_hash_request,
        Fetch({archive_url: [(200, archive)], checksum_url: [(200, checksum)]}),
    )
    assert wrong_hash.result is None
    assert wrong_hash.failure is not None
    assert wrong_hash.failure.code is BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.SOURCE_HASH_MISMATCH

    archive, malformed_checksum = evidence(checksum_separator=" ")
    malformed_request = request_for(archive, malformed_checksum)
    archive_url, checksum_url = malformed_request.urls
    malformed = capture_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        malformed_request,
        Fetch(
            {
                archive_url: [(200, archive)],
                checksum_url: [(200, malformed_checksum)],
            }
        ),
    )
    assert malformed.result is None
    assert malformed.failure is not None
    assert malformed.failure.code is BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.SOURCE_HASH_MISMATCH

    wrong_date_request = request_for(
        archive,
        checksum,
        utc_date="2026-07-17",
        archive_available_at=ACQUIRED_AT,
    )
    archive_url, checksum_url = wrong_date_request.urls
    wrong_date = capture_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        wrong_date_request,
        Fetch({archive_url: [(200, archive)], checksum_url: [(200, checksum)]}),
    )
    assert wrong_date.result is None
    assert wrong_date.failure is not None

    btc_archive, btc_checksum = evidence(
        member_name="BTCUSDT-aggTrades-2026-07-16.csv",
        checksum_name="BTCUSDT-aggTrades-2026-07-16.zip",
    )
    btc_request = request_for(btc_archive, btc_checksum)
    archive_url, checksum_url = btc_request.urls
    btc = capture_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        btc_request,
        Fetch(
            {
                archive_url: [(200, btc_archive)],
                checksum_url: [(200, btc_checksum)],
            }
        ),
    )
    assert btc.result is None
    assert btc.failure is not None


@pytest.mark.parametrize(
    ("archive_responses", "expected_code", "expected_attempts"),
    [
        ([RuntimeError("offline"), (503, b""), (200, evidence()[0])], None, 3),
        (
            [(500, b""), (500, b""), (500, b"")],
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.PROVIDER_UNAVAILABLE,
            3,
        ),
        (
            [(429, b""), (429, b""), (429, b"")],
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.RATE_LIMIT_EXHAUSTED,
            3,
        ),
        (
            [(403, b"")],
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.AUTHENTICATION_REJECTED,
            1,
        ),
        (
            [(404, b"")],
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.DATA_GAP_DETECTED,
            1,
        ),
    ],
)
def test_capture_http_retry_classification(
    archive_responses: list[tuple[int, bytes] | Exception],
    expected_code: BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1 | None,
    expected_attempts: int,
) -> None:
    archive, checksum = evidence()
    request = request_for(archive, checksum)
    archive_url, checksum_url = request.urls
    outcome = capture_binance_usdm_koru_aggregate_trades_source_bounded_v1(
        request,
        Fetch(
            {
                archive_url: archive_responses.copy(),
                checksum_url: [(200, checksum)],
            }
        ),
    )
    if expected_code is None:
        assert outcome.failure is None
        assert outcome.result is not None
        assert outcome.result.archive_attempts == expected_attempts
    else:
        assert outcome.result is None
        assert outcome.failure is not None
        assert outcome.failure.code is expected_code


@pytest.mark.parametrize(
    ("rows", "expected_code"),
    [
        (
            (("agg_trade_id", "price", "qty", "first", "last", "time", "maker"),)
            + ROWS,
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.SOURCE_SCHEMA_MISMATCH,
        ),
        (
            (("700", "01.0", "1.250", "900", "901", str(DAY_START_MS + 1_000), "true"),)
            + ROWS[1:],
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.NORMALIZATION_FAILED,
        ),
        (
            (("700", "12.340", "1.250", "900", "901", str(DAY_START_MS + 1_000), "TRUE"),)
            + ROWS[1:],
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.NORMALIZATION_FAILED,
        ),
        (
            (ROWS[0], ("699", "12.350", "2.000", "902", "903", str(DAY_START_MS + 2_000), "false")),
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.ORDER_VIOLATION,
        ),
        (
            (ROWS[0], ROWS[0]),
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.DUPLICATE_OR_CONFLICT,
        ),
        (
            (ROWS[0], ("700", "99.0", "2.000", "902", "903", str(DAY_START_MS + 2_000), "false")),
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.DUPLICATE_OR_CONFLICT,
        ),
        (
            (ROWS[0], ("702", "12.350", "2.000", "902", "903", str(DAY_START_MS + 2_000), "false")),
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.DATA_GAP_DETECTED,
        ),
        (
            (ROWS[0], ("701", "12.350", "2.000", "902", "903", str(DAY_START_MS + 500), "false")),
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.ORDER_VIOLATION,
        ),
        (
            (("700", "12.340", "1.250", "900", "901", str(DAY_START_MS - 1), "true"),),
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.DATA_GAP_DETECTED,
        ),
    ],
)
def test_normalization_rejects_header_decimal_boolean_order_duplicate_gap_and_time(
    rows: tuple[tuple[str, ...], ...],
    expected_code: BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1,
) -> None:
    outcome = normalize(rows)
    assert outcome.result is None
    assert outcome.failure is not None
    assert outcome.failure.code is expected_code


@pytest.mark.parametrize(
    ("second_first_trade_id", "expected_code"),
    [
        (
            "903",
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.DATA_GAP_DETECTED,
        ),
        (
            "901",
            BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.DUPLICATE_OR_CONFLICT,
        ),
    ],
)
def test_normalization_requires_contiguous_raw_trade_ranges(
    second_first_trade_id: str,
    expected_code: BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1,
) -> None:
    rows = (
        ROWS[0],
        (
            "701",
            "12.350",
            "2.000",
            second_first_trade_id,
            "903",
            str(DAY_START_MS + 2_000),
            "false",
        ),
    )
    outcome = normalize(rows)
    assert outcome.result is None
    assert outcome.failure is not None
    assert outcome.failure.code is expected_code


def test_normalization_rejects_wrong_zip_member_and_source_snapshot_mutation() -> None:
    wrong_member = normalize(member_name="KORUUSDT-aggTrades-2026-07-17.csv")
    assert wrong_member.result is None
    assert wrong_member.failure is not None
    assert wrong_member.failure.code is BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.SOURCE_SCHEMA_MISMATCH

    captured = capture()
    object.__setattr__(captured.snapshot, "archive_bytes", captured.snapshot.archive_bytes + b"x")
    mutated = normalize_binance_usdm_koru_aggregate_trades_source_bounded_v1(captured)
    assert mutated.result is None
    assert mutated.failure is not None
    assert mutated.failure.code is BinanceUsdmKoruAggregateTradesSourceBoundedFailureCodeV1.CONFIGURATION_INVALID


def test_three_rows_do_not_claim_full_day_and_forged_full_day_coverage_fails() -> None:
    result = normalize().result
    assert result is not None
    assert result.coverage_start != result.requested_day_start
    assert result.coverage_end_exclusive != result.requested_day_end_exclusive
    with pytest.raises(ValueError, match="exactly reconstruct"):
        replace(
            result,
            coverage_start=result.requested_day_start,
            coverage_end_exclusive=result.requested_day_end_exclusive,
        )


def test_normalization_result_reconstructs_exact_retained_events_and_rejects_mutations() -> None:
    result = normalize().result
    assert result is not None
    first = result.events[0]
    mutations: tuple[MarketEvent, ...] = (
        replace(first, event_id=first.event_id + "-forged"),
        replace(first, payload={**first.payload, "extra_payload_key": "forged"}),
        replace(
            first,
            payload={**first.payload, "source_record_hash": "sha256:" + "0" * 64},
        ),
        replace(
            first,
            payload={**first.payload, "checksum_member_hash": "sha256:" + "0" * 64},
        ),
        replace(first, payload={**first.payload, "price_purpose": "mark_price"}),
    )
    for mutated_event in mutations:
        with pytest.raises(ValueError, match="exactly reconstruct"):
            replace(result, events=(mutated_event,) + result.events[1:])


def test_normalization_outcome_rejects_post_construction_event_mutation() -> None:
    result = normalize().result
    assert result is not None
    object.__setattr__(result.events[0], "event_id", result.events[0].event_id + "-forged")
    with pytest.raises(ValueError, match="not canonical"):
        BinanceUsdmKoruAggregateTradesSourceBoundedNormalizationOutcomeV1(result=result)
